# Generated by Django 5.1.2 on 2024-12-15 11:53

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquelink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uniquelink',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 17, 13, 52, 46, 505233, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='uniquelink',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
