# Generated by Django 5.1.2 on 2024-12-13 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniquelink',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 14, 8, 40, 45, 526200, tzinfo=datetime.timezone.utc)),
        ),
    ]
