# Generated by Django 5.1.2 on 2024-12-15 12:00

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_uniquelink_created_at_uniquelink_expired_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniquelink',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 17, 14, 0, 39, 664109, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='uniquelink',
            name='link',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
