# Generated by Django 5.1.2 on 2024-12-14 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_message_date_alter_uniquelink_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniquelink',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 15, 16, 34, 51, 178420, tzinfo=datetime.timezone.utc)),
        ),
    ]
