# Generated by Django 5.1.2 on 2024-12-15 09:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_uniquelink_expired_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniquelink',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='uniquelink',
            name='is_expired',
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='uniquelink',
            name='expired_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='uniquelink',
            name='link',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
