# Generated by Django 5.1.2 on 2024-12-15 10:06

import datetime
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_remove_uniquelink_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquelink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uniquelink',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='uniquelink',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 15, 12, 6, 22, 811300, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='uniquelink',
            name='link',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
